global:
  scrape_interval:     30s
  evaluation_interval: 10s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  #- job_name: 'docker'
  #  static_configs:
  #    - targets: ['docker:9323'] 

  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'collectd'
    static_configs:
      - targets: ['collectd:9103']

  - job_name: 'unifipoller'
    static_configs:
      - targets: ['unifipoller:9130']

  #- job_name: 'pushgateway'
  #  honor_labels: true
  #  static_configs:
  #    - targets: ['pushgateway:9091']


#alerting:
#  alertmanagers:
#  - scheme: http
#    static_configs:
#    - targets: 
#      - 'alertmanager:9093'

#  - job_name: 'aspnetcore'
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
