{
 "title": "Node Exporter for Prometheus",
 "description": "【English version】Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{instance=~\"$node\"} / node_memory_SwapTotal_bytes{instance=~\"$node\"})) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',mountpoint=~\"/mnt/btrfs|/overlay|/storage\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node',mountpoint=~\"/mnt/btrfs|/overlay|/storage\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',mountpoint=~\"/mnt/btrfs|/overlay|/storage\"} / node_filesystem_size_bytes{instance=~'$node',mountpoint=~\"/mnt/btrfs|/overlay|/storage\"})"
    }
   ]
  },
  {
   "title": "Open  File Descriptor / Context switches",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}",
     "legendFormat": "filefd"
    },
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\"}[30m])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU IOwait",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/ receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[40s])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[40s])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',mountpoint=~\"/mnt/btrfs|/overlay|/storage\"} / node_filesystem_size_bytes{instance=~'$node',mountpoint=~\"/mnt/btrfs|/overlay|/storage\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=~'$node'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "node_memory_AnonPages_bytes{instance=~'$node'}",
     "legendFormat": "AnonPages"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~'$node'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~'$node'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Dirty_bytes{instance=~'$node'}",
     "legendFormat": "Dirty"
    },
    {
     "expr": "node_memory_Inactive_bytes{instance=~'$node'}",
     "legendFormat": "Inactive"
    },
    {
     "expr": "node_memory_Mapped_bytes{instance=~'$node'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\"}[50s])",
     "legendFormat": "{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "iops", "label": "IO writes (-) / reads (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$node\",device=~'(md0|nvme0n1)'}[50s])",
     "legendFormat": "{{device}}_Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$node\",device=~'(md0|nvme0n1)'}[50s])",
     "legendFormat": "{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bps", "label": "written（-）/ read（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\",device=~'(md0|nvme0n1)'}[40s])*8",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\",device=~'(md0|nvme0n1)'}[40s])*8",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk R/W Time",
   "type": "graph",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "s", "label": "Time writing (-) / reading (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$node\"}[40s])",
     "legendFormat": "{{device}}_Read time"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$node\"}[40s])",
     "legendFormat": "{{device}}_Write time"
    }
   ]
  },
  {
   "title": "Processes CPU",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(rate(collectd_processes_ps_cputime_user_total[40s]) + rate(collectd_processes_ps_cputime_syst_total[40s])) / (10000*15*8)",
     "legendFormat": "{{processes}}"
    }
   ]
  },
  {
   "title": "Processes Memory",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (processes) (collectd_processes_ps_data)",
     "legendFormat": "{{processes}}"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$node'}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
     "legendFormat": "TCP_inuse"
    },
    {
     "expr": "node_sockstat_RAW_inuse{instance=~'$node'}",
     "legendFormat": "RAW_inuse"
    },
    {
     "expr": "node_sockstat_TCP_orphan{instance=~'$node'}",
     "legendFormat": "TCP_orphan"
    }
   ]
  },
  {
   "title": "Hardware Temperature",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~'$node'}",
     "legendFormat": "{{chip}}_{{sensor}}"
    }
   ]
  }
 ]
}