{
 "title": "OpenWRT",
 "description": "Dashboard for OpenWRT routers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "name",
    "label": "Host:",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{nodename=\"$name\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_uname_info{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node:$port\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (5m avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Used Root FS",
   "type": "singlestat",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/overlay\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/overlay\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node:$port\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Total Network Traffic",
   "type": "singlestat",
   "description": "Total network traffic",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "expr": "(sum(node_network_transmit_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}) + sum(node_network_receive_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}))"
    }
   ]
  },
  {
   "title": "Total NAT Traffic",
   "type": "singlestat",
   "description": "Total NAT traffic (WAN)",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_nat_traffic{instance=~\"$node:$port\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/overlay\",fstype!=\"rootfs\"}"
    }
   ]
  },
  { "title": "CPU Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"} - (node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Slab_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_PageTables_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapCached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Unused - Free memory unasigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Memory Detail Meminfo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Active / Inactive",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
      },
      {
       "expr": "node_memory_Active_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
      }
     ]
    },
    {
     "title": "Memory Commited",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
      },
      {
       "expr": "node_memory_CommitLimit_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
      }
     ]
    },
    {
     "title": "Memory Active / Inactive Detail",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Inactive_file_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Inactive_file - File-backed memory on inactive LRU list"
      },
      {
       "expr": "node_memory_Inactive_anon_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Inactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
      },
      {
       "expr": "node_memory_Active_file_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Active_file - File-backed memory on active LRU list"
      },
      {
       "expr": "node_memory_Active_anon_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Active_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs"
      }
     ]
    },
    {
     "title": "Memory Writeback and Dirty",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Writeback - Memory which is actively being written back to disk"
      },
      {
       "expr": "node_memory_WritebackTmp_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
      },
      {
       "expr": "node_memory_Dirty_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
      }
     ]
    },
    {
     "title": "Memory Shared and Mapped",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Mapped_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Mapped - Used memory in mapped pages files which have been mmaped, such as libraries"
      },
      {
       "expr": "node_memory_Shmem_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Shmem - Used shared memory (shared between several processes, thus including RAM disks)"
      }
     ]
    },
    {
     "title": "Memory Slab",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_SUnreclaim_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure"
      },
      {
       "expr": "node_memory_SReclaimable_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "SReclaimable - Part of Slab, that might be reclaimed, such as caches"
      }
     ]
    },
    {
     "title": "Memory Vmalloc",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_VmallocChunk_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "VmallocChunk - Largest contigious block of vmalloc area which is free"
      },
      {
       "expr": "node_memory_VmallocTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
      }
     ]
    },
    {
     "title": "Memory Kernel",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_KernelStack_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "KernelStack - Kernel memory stack. This is not reclaimable"
      }
     ]
    },
    {
     "title": "Memory Anonymous",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_AnonHugePages_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "AnonHugePages - Memory in anonymous huge pages"
      },
      {
       "expr": "node_memory_AnonPages_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "AnonPages - Memory in user pages not backed by files"
      }
     ]
    },
    {
     "title": "Memory Unevictable and MLocked",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Unevictable_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "Unevictable - Amount of unevictable memory that can't be swapped out for a variety of reasons"
      },
      {
       "expr": "node_memory_Mlocked_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
       "legendFormat": "MLocked - Size of pages locked to memory using the mlock() system call"
      }
     ]
    }
   ]
  },
  { "title": "System Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Context Switches / Interrupts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Counter" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "Context switches"
    },
    {
     "expr": "irate(node_intr_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Processes CPU",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(rate(collectd_processes_ps_cputime_user_total[40s]) + rate(collectd_processes_ps_cputime_syst_total[40s])) / (10000*15*8)",
     "legendFormat": "{{processes}}"
    }
   ]
  },
  {
   "title": "Processes Memory",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (processes) (collectd_processes_ps_data)",
     "legendFormat": "{{processes}}"
    }
   ]
  },
  {
   "title": "Processes  Forks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Forks / sec" }
   ],
   "targets": [
    {
     "expr": "rate(node_forks_total{instance=~\"$node:$port\",job=~\"$job\"}[40s])",
     "legendFormat": "Processes forks second"
    }
   ]
  },
  {
   "title": "File Descriptor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Files" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Open files"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Network Receive Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[40s])*8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmit Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[40s])*8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Receive Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=~\"$node:$port\",job=~\"$job\"}[40s])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmit Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total{instance=~\"$node:$port\",job=~\"$job\"}[40s])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Bytes Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (rate(node_network_receive_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[40s]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Bytes Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (rate(node_network_transmit_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[40s]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Network Traffic Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Nginx Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(collectd_nginx_connections_total[5m])",
     "legendFormat": "{{nginx}}"
    },
    {
     "expr": "collectd_nginx_nginx_connections",
     "legendFormat": "{{nginx}}"
    }
   ]
  },
  {
   "title": "DNS qtype",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dns) (collectd_dns_dns_qtype_total)",
     "legendFormat": "{{dns}}"
    }
   ]
  },
  {
   "title": "DNS rcode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dns) (collectd_dns_dns_rcode_total)",
     "legendFormat": "{{dns}}"
    }
   ]
  },
  {
   "title": "NF Contrack",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "NF conntrack entries"
    }
   ]
  },
  {
   "title": "Network Traffic Multicast",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_multicast_total{instance=~\"$node:$port\",job=~\"$job\"}[40s])",
     "legendFormat": "{{device}} - Receive multicast"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{instance=~\"$node:$port\",job=~\"$job\"}[40s])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{instance=~\"$node:$port\",job=~\"$job\"}[40s])",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{instance=~\"$node:$port\",job=~\"$job\"}[40s])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{instance=~\"$node:$port\",job=~\"$job\"}[40s])",
     "legendFormat": "{{device}} - Transmit errors"
    }
   ]
  }
 ]
}