{
 "title": "Smartmon",
 "description": "Smartmon Texfile node_exporter Dashboard",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(smartmon_smartctl_version, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unhealthy Disks",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "smartmon_device_smart_healthy{instance=~\"$instance\"} < 1"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(smartmon_temperature_celsius_raw_value{instance=~\"$instance\", disk!='/dev/sda'}) by (instance, disk)",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Error Read Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(smartmon_raw_read_error_rate_raw_value{instance=~\"$instance\"}) by (instance, disk)",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Reallocated Event Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartmon_reallocated_event_count_raw_value{instance=~\"$instance\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Current Pending Sectors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartmon_current_pending_sector_raw_value{instance=~\"$instance\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Offline Uncorrectable Sectors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartmon_offline_uncorrectable_raw_value{instance=~\"$instance\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Load Cycle Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "smartmon_load_cycle_count_raw_value{instance=~\"$instance\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Power Cycle Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "smartmon_power_cycle_count_raw_value{instance=~\"$instance\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Spin Up Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "smartmon_spin_up_time_raw_value{instance=~\"$instance\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Power On Hours",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "expr": "smartmon_power_on_hours_raw_value{instance=~\"$instance\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  }
 ]
}