{
 "title": "UniFi-Poller: Client Insights",
 "description": "UniFi Poller v2.0 Displays detailed information for clients in a UniFi network using Prometheus.",
 "tags": [
  "unifi",
  "unifi-poller"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "label_values(unifipoller_client_uptime_seconds,source)"
   },
   {
    "name": "Site",
    "query": "label_values(unifipoller_client_uptime_seconds{source=~\"$Controller\"},site_name)"
   },
   {
    "name": "AP",
    "query": "label_values(unifipoller_client_uptime_seconds{site_name=~\"$Site\"},ap_name)"
   },
   {
    "name": "Switch",
    "query": "label_values(unifipoller_client_uptime_seconds{site_name=~\"$Site\"},sw_name)"
   },
   {
    "name": "Wireless",
    "query": "label_values(unifipoller_client_uptime_seconds{site_name=~\"$Site\", ap_name=~\"$AP\", wired=\"false\"},name)"
   },
   {
    "name": "Wired",
    "query": "label_values(unifipoller_client_uptime_seconds{site_name=~\"$Site\", sw_name=~\"$Switch\", wired=\"true\"},name)"
   },
   {
    "name": "Smooth",
    "query": "5s,15s,30s,1m,2m,5m,10m,15m,30m,1h"
   }
  ]
 },
 "panels": [
  {
   "title": "Wireless Devices",
   "type": "table-old",
   "description": "This table represents current (latest) data.\nBytes columns are lifetime totals.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unifipoller_client_receive_bytes_total{wired!=\"true\", site_name=~\"$Site\", name=~\"$Wireless\"})"
    },
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unifipoller_client_transmit_bytes_total{wired!=\"true\",site_name=~\"$Site\", name=~\"$Wireless\"})"
    },
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unifipoller_client_uptime_seconds{wired!=\"true\",site_name=~\"$Site\", name=~\"$Wireless\"})"
    }
   ]
  },
  {
   "title": "Clients / Channel",
   "type": "grafana-piechart-panel",
   "description": "Visualize wireless channel usage w/ wired client counts.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (hostname) (unifipoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})",
     "legendFormat": "Wired"
    },
    {
     "expr": "count by (channel) (unifipoller_client_roam_count_total{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\"})",
     "legendFormat": "Channel {{channel}}"
    }
   ]
  },
  {
   "title": "Clients / AP Radio",
   "type": "grafana-piechart-panel",
   "description": "Visualize how many clients are connected to which radios/APs.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (radio_proto) (unifipoller_client_roam_count_total{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\"})",
     "legendFormat": "{{radio_proto}}"
    }
   ]
  },
  {
   "title": "Client MAC OUI Breakdown",
   "type": "grafana-piechart-panel",
   "description": "This shows an OUI breakdown from Unifi's perspective. e = wired, w = wireless",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (oui) (unifipoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\"})",
     "legendFormat": " w {{oui}}"
    },
    {
     "expr": "count by (oui) (+unifipoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})",
     "legendFormat": "e  {{oui}}"
    }
   ]
  },
  {
   "title": "UAP Bandwidth / Wireless Devices",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bps", "label": "Tx (-) / Rx (+)" }
   ],
   "targets": [
    {
     "expr": "rate(unifipoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[15s])*8",
     "legendFormat": "{{name}} Tx"
    },
    {
     "expr": "rate(unifipoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[15s])*8",
     "legendFormat": "{{name}} Rx"
    }
   ]
  },
  {
   "title": "Received Signal Strength Indicator",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "dB", "label": "RSSI Quality" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (unifipoller_client_rssi_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Wireless Signal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "dBm", "label": "Signal Power" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (unifipoller_client_radio_signal_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Client Satisfaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percentunit", "label": "Client Satisfaction" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (unifipoller_client_satisfaction_ratio{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Client Wifi Tx Attempts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "Attempts / Second" }
   ],
   "targets": [
    {
     "expr": "rate(unifipoller_client_wifi_attempts_transmit_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}[$__interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Client Transmit Retries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Tx Retries / Second" }
   ],
   "targets": [
    {
     "expr": "rate(unifipoller_client_transmit_retries_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}[$__interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "UAP Client Stats / Noise",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "dB", "label": "Noise" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (unifipoller_client_noise_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "TX Rate",
   "type": "graph",
   "description": "Client reported transmit rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (unifipoller_client_radio_receive_rate_bps{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RX Rate",
   "type": "graph",
   "description": "Client reported receive rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (unifipoller_client_radio_transmit_rate_bps{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}